### ISSUE TITLE
Installation and output image issues

### ISSUE THREAD

**Issue by fernandomeyer** [dkoslicki/CAMIProfilingVisualization#14]
After installation with the provided instructions in a docker container (ubuntu:20.04), running profile_to_plot.py gives the following error:

```
python profile_to_plot.py -g /host/projects/tutorial/profiles/cami2_mouse_gut_gs.profile -i /host/projects/tutorial/profiles/cami2_mouse_gut_metaphlan2.2.0.profile family -b x -t pdf
Traceback (most recent call last):
  File "profile_to_plot.py", line 2, in <module>
    from ProfilesLayout import ProfilesLayout
  File "/host/tmp/CAMIProfilingVisualization/src/ProfilesLayout.py", line 2, in <module>
    from ete3 import Tree, faces, TreeStyle, COLOR_SCHEMES, TextFace
ImportError: cannot import name 'faces'
```

This can be solved by installing libgl1:

```
apt update
apt install --no-install-recommends libgl1
```

Running profile_to_plot.py then gives another error:

```
python profile_to_plot.py -g /host/projects/tutorial/profiles/cami2_mouse_gut_gs.profile -i /host/projects/tutorial/profiles/cami2_mouse_gut_metaphlan2.2.0.profile family -b x -t pdf
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Done. Parsing...
Loading node names...
2268061 names loaded.
225307 synonyms loaded.
Loading nodes...
2268061 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /root/.etetoolkit/taxa.sqlite ...
 2268000 generating entries... 
Uploading to /root/.etetoolkit/taxa.sqlite

Inserting synonyms:      140000 Traceback (most recent call last):
  File "profile_to_plot.py", line 12, in <module>
    ncbi = NCBITaxa()
  File "/root/miniconda3/envs/CAMIViz/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 110, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/root/miniconda3/envs/CAMIViz/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 129, in update_taxonomy_database
    update_db(self.dbfile)
  File "/root/miniconda3/envs/CAMIViz/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 760, in update_db
    upload_data(dbfile)
  File "/root/miniconda3/envs/CAMIViz/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 802, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid
```

A workaround for this is to replace INSERT INTO by INSERT OR IGNORE INTO in line 802 of ncbiquery.py, then remove /root/.etetoolkit/ before running profile_to_plot.py again.

Finally, this is the image I get (characters are not legible and the circles are missing):

[x_tree_family.pdf](https://github.com/dkoslicki/CAMIProfilingVisualization/files/5089988/x_tree_family.pdf)

In a local, manually created environment (without docker and conda), I get an image with legible characters but the circles are still missing. No errors are reported at this step.

**Comment by dkoslicki** [comment]
@Addicted-to-coding has this been addressed?

**Comment by Addicted-to-coding** [comment]
@fernandomeyer we have updated the tool. Can you please ping us if you still get an error?
