### ISSUE TITLE
cannot run the tool with conda

### ISSUE THREAD

**Issue by AlessioMilanese** [dkoslicki/CAMIProfilingVisualization#17]
Thanks for implementing TAMPA. I installed the tool with conda:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -c etetoolkit -y -n CAMIViz python=3.7 numpy  ete3  seaborn pandas matplotlib biom-format
conda activate CAMIViz
```

But when I try to run `python src/profile_to_plot.py` within the CAMIViz env, I get the following error:
```
python: can't open file 'src/profile_to_plot.py': [Errno 2] No such file or directory
```

**Comment by Addicted-to-coding** [comment]
Sorry about that, we have renamed profile_to_plot.py to tampa.py. The README as also been updated. Could you please try running it again?

**Comment by AlessioMilanese** [comment]
Thanks for the response. 

I had an error while trying to install with github:
```
$ git clone git@github.com:dkoslicki/TAMPA.git

Cloning into 'TAMPA'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

which I solved with:
```
git clone https://github.com/dkoslicki/TAMPA
```

**Comment by AlessioMilanese** [comment]
I'm not sure what I'm doing wrong. But if I try to run the test example, I get an error:
```
$ python src/tampa.py -i data/prediction_multi.profile -g data/ground_truth_multi.profile phylum -s CAMI_HIGH_S001 -b basename -k linear -c False -r 1600 -o .

False
CAMI_HIGH_S001
Traceback (most recent call last):
  File "src/tampa.py", line 337, in <module>
    if __name__ == "__main__": main()
  File "src/tampa.py", line 334, in main
    generateFigure(PF, sample, rank, output_base_name, output_path, file_type, plot_l1, scaling, output_dpi, use_profile, fw, fh, limit, limit_value)
  File "src/tampa.py", line 106, in generateFigure
    PF.make_tax_id_to_percentage(sample=sample)
  File "/Users/milanese/Desktop/TAMPA/src/ProfilesLayout.py", line 168, in make_tax_id_to_percentage
    self.profile_tax_id_to_percentage = self.predictions_to_tax_id('profile', sample)
  File "/Users/milanese/Desktop/TAMPA/src/ProfilesLayout.py", line 151, in predictions_to_tax_id
    predictions = sample_dict[sample]['predictions']
KeyError: 'CAMI_HIGH_S001'
```

**Comment by Addicted-to-coding** [comment]
Sorry about that, could you please try 
python src/tampa.py -i data/mad_yalow_0.profile.txt -g data/ecstatic_nobel_0.profile.txt phylum -s marmgCAMI2_short_read_sample_0 -b metaphlan_motu -k linear -r 1600  -o .

**Comment by AlessioMilanese** [comment]
I get:
```
$ python src/tampa.py -i data/mad_yalow_0.profile.txt -g data/ecstatic_nobel_0.profile.txt phylum -s marmgCAMI2_short_read_sample_0 -b metaphlan_motu -k linear -r 1600 -o .

False
Input file could not be read.
```

**Comment by AlessioMilanese** [comment]
And actually `data/mad_yalow_0.profile.txt` is not in the repo:
```
$ ls data/mad_yalow_0.profile.txt
ls: data/mad_yalow_0.profile.txt: No such file or directory
```

**Comment by Addicted-to-coding** [comment]
The push must've failed.
Could you please try 
python src/tampa.py -i data/mad_yalow_0.profile.txt -g data/gs_marine_short.profile.txt class -s marmgCAMI2_short_read_sample_0 -b marine_test -k linear -r 1600 -c False -o .

instead?

**Comment by AlessioMilanese** [comment]
Thanks for the fast response. It works now.
