### ISSUE TITLE
help not working

### ISSUE THREAD

**Issue by AlessioMilanese** [dkoslicki/CAMIProfilingVisualization#18]
Hi,

when I try to check the help function (`python src/tampa.py -h`), it does not work for me:
```
python src/tampa.py -h
Traceback (most recent call last):
  File "src/tampa.py", line 337, in <module>
    if __name__ == "__main__": main()
  File "src/tampa.py", line 264, in main
    params = argparser.parse_args()
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 1043, in __call__
    parser.print_help()
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 2481, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 2465, in format_help
    return formatter.format_help()
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 531, in _format_action
    help_text = self._expand_help(action)
  File "/Users/milanese/miniconda3/envs/CAMIViz/lib/python3.7/argparse.py", line 620, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character ',' (0x2c) at index 95
```

**Comment by Addicted-to-coding** [comment]
I've updated the readme. Can you please try python src/tampa.py

**Comment by AlessioMilanese** [comment]
This is what I get:
```
$ python src/tampa.py
usage: tampa.py [-h] [-i INPUT_PROFILE] [-i1 INPUT_PROFILE1]
                [-g GROUND_TRUTH_INPUT_PROFILE] [-b OUTPUT_BASE_NAME]
                [-t FILE_TYPE] [-s SAMPLE_OF_INTEREST] [-k SCALING]
                [-a LABELS] [-y LAYOUT] [-l] [-n] [-m] [-d DB_FILE] [-r RES]
                [-p] [-top TOP] [-thr THR] [-fs FONTSIZE] [-ls LABELSIZE]
                [-lw LABELWIDTH] [-bm BRANCHMARGIN] [-lsep LEAF_SEP]
                [-fh FIGHEIGHT] [-fw FIGWIDTH] [-nm] [-o OUTPUT_PATH]
                [-dt HIGHLIGHT_DIFFERENCES_THRESHOLD] [-c CONTRAST]
                taxonomic_rank
tampa.py: error: the following arguments are required: taxonomic_rank
```

**Comment by Addicted-to-coding** [comment]
Yes, listed above are the various options TAMPA provides.

**Comment by AlessioMilanese** [comment]
Thanks.
